"""add video file identity

Revision ID: d037dd01d9c9
Revises: b79bcc5df14a
Create Date: 2026-07-16 10:16:49.461089

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd037dd01d9c9'
down_revision: str | Sequence[str] | None = 'b79bcc5df14a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('file_sha256', sa.String(length=64), nullable=True))
    op.add_column('videos', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('uq_videos_file_sha256', 'videos', ['file_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_videos_file_sha256', 'videos', type_='unique')
    op.drop_column('videos', 'file_size_bytes')
    op.drop_column('videos', 'file_sha256')
    # ### end Alembic commands ###
