"""add visit event key

Revision ID: dbdf72fb9367
Revises: 21f5b49cfe44
Create Date: 2026-07-07 19:09:16.862095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdf72fb9367'
down_revision: Union[str, Sequence[str], None] = '21f5b49cfe44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('event_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_visits_event_key', 'visits', ['event_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_visits_event_key', 'visits', type_='unique')
    op.drop_column('visits', 'event_key')
    # ### end Alembic commands ###
